In [82]:
# Carregando o conjunto de dados
import pandas as pd
arquivo = pd.read_csv('./dados_vinhos.csv')
arquivo.shape

(6497, 13)

In [83]:
arquivo.head() # Para visualizar o conjunto de dados no python (5 primeiras linhas padrão)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [84]:
arquivo['style'] = arquivo['style'].replace('red', 0) # Transforma ou "troca" valores da coluna descrita
arquivo['style'] = arquivo['style'].replace('white', 1) # Transforma ou "troca" valores da coluna descrita

In [85]:
tipo = arquivo['style'] # Variável alvo (o que quero prever)
dados = arquivo.drop('style', axis = 1) # Restante dos dados

In [86]:
from sklearn.model_selection import train_test_split

# Cria conjustos para treino e também para testes
x_treino, x_teste, y_treino, y_teste = train_test_split(dados, tipo, test_size = 0.3)

In [87]:
from sklearn.ensemble import ExtraTreesClassifier
# Criando o modelo
modelo = ExtraTreesClassifier()
modelo.fit(x_treino,y_treino)

resultado = modelo.score(x_teste,y_teste) # Vai comparar os dados de treino com os reais
print("Acurácia:", resultado)

Acurácia: 0.9953846153846154

In [88]:
y_teste[0:10]

C:\Users\55229\AppData\Local\Temp\ipykernel_7628\938560834.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  y_teste[0:10]

2835    1
5443    1
6492    1
6383    1
6011    1
3841    1
4501    1
3316    1
3341    1
12      0
Name: style, dtype: int64

In [89]:
x_teste[0:10]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
2835,6.8,0.320,0.37,3.4,0.023,19.0,87.0,0.99020,3.14,0.53,12.7,6
5443,6.7,0.370,0.25,2.5,0.028,24.0,84.0,0.99090,3.14,0.36,11.7,6
6492,6.2,0.210,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
6383,6.4,0.310,0.31,12.9,0.045,55.0,161.0,0.99546,3.02,0.59,10.2,5
6011,7.1,0.270,0.27,10.4,0.041,26.0,114.0,0.99335,3.04,0.52,11.5,7
3841,6.1,0.230,0.45,10.6,0.094,49.0,169.0,0.99699,3.05,0.54,8.8,5
4501,6.2,0.360,0.14,8.9,0.036,38.0,155.0,0.99622,3.27,0.50,9.4,5
3316,6.8,0.270,0.32,1.5,0.044,19.0,142.0,0.99210,3.10,0.43,9.9,6
3341,6.3,0.250,0.23,14.9,0.039,47.0,142.0,0.99705,3.14,0.35,9.7,6
12,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.99430,3.58,0.52,9.9,5

In [90]:
previsoes = modelo.predict(x_teste[0:10])
print(previsoes)

[1 1 1 1 1 1 1 1 1 0]